### ISSUE TITLE
How to supply local source

### ISSUE THREAD

**Issue by Rahulsharma0810** [gdmoney/gcp-cloud-functions-github-actions#1]
HI,

Thanks for the guide

my directory structure is 

```
├── .github
│   └── workflows
│       └── main.yml
├── .gitignore
├── LICENSE
├── README.md
└── src
    ├── main.py
    └── requirements.txt
```

How do I deploy main.py, It says

`Deployment failure:
Build failed: missing main.py and GOOGLE_FUNCTION_SOURCE not specified. Either create the function in main.py or specify GOOGLE_FUNCTION_SOURCE to point to the file that contains the function; Error ID: 5c04ec9c`

**Comment by gdmoney** [comment]
Hi, I'm glad you found it useful.

This example assumes that your GH repo is synced with GCP Cloud Source Repositories. The `source` is pointing to the Cloud Source Repositories directory containing the `main.py` code. If you're not syncing repos, your source would be a local Zip file containing the main.py code.
